#!/home/exacloud/lustre1/users/yoshiokc/sw/cky-tools/site/bin/python

import os
import re
import sh
import glob
import numpy as np
from collections import defaultdict as ddict

import imaging

proc2d = sh.Command('e2proc2d.py')

def arguments():
    
    import argparse

    def floatlist(string):
        return tuple(map(float, string.split(',')))

    parser = argparse.ArgumentParser(
        description="normalize raw frame stacks")
    parser.add_argument('-i', '--src', required=True,
                        help='directory with EPU MRC frames')
    parser.add_argument('-o', '--dst', required=True,
                        help='directory to output merged MRCS files')
    parser.add_argument('-p', '--processes', default=1, type=int,
                        help='number of stacks to process in parallel')
    return parser.parse_args()


def merge_mrcs(mrcs, merged):
    for mrc in mrcs:
        proc2d(mrc, merged)
    #base,_ = os.path.splitext(merged)
    #avg = base + '.mrc'
    #proc2d(merged, avg, '--average')
    print('->', merged)


def main():
    args = arguments()
    frames = glob.glob(os.path.join(args.src, '*_frames*.mrc'))
    movies = ddict(dict)
    for frame in frames:
        path, fid = re.search('(.+)_frames_n(\d+).mrc', frame).groups()
        movies[path][int(fid)] = frame
    import multiprocessing as mp
    pool = mp.Pool(args.processes)
    done = 0
    for base in movies:
        movie_path = os.path.join(args.dst, os.path.basename(base) + '.mrcs')
        movie_frames = [movies[base][fid] for fid in sorted(movies[base])]
        def progress():
            nonlocal done
            print(movie_path)
            for frame in movie_frames:
                print('   +', frame)
            done += 1
            print(' done: %d of %d' % (done, len(movies)))
        pool.apply_async(merge_mrcs, args=(movie_frames, movie_path))
        #merge_mrcs(movie_frames, movie_path)
    pool.close()
    pool.join()


if __name__ == '__main__':
    main()
